from os import system as sistem
from random import randrange
while True:
    print("SAJT 32")
    sistem(f"color {randrange(0,7)}")
    sistem(f"color {randrange(19,40)}")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")
    print("SAJT 32", end=" ")